version: 1.0
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  <{{project.name}}>
Globals:
  Function:
    Timeout: 10
Resources:
  <{{project.lambda.name}}>:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: index.handler
      Runtime: nodejs18.x
      Events:
        <{{project.lambda.event}}>:
          Type: Api
          Properties:
            Path: <{{project.lambda.path}}>
            Method: <{{project.lambda.method}}>  